spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laefad/configuration_repository
          skipSslValidation: true
  security:
    user:
      name: user
      password: password

server:
  port: 8000

