spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laefad/configuration_repository
          skipSslValidation: true
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8000

