version: '3.8'

x-deploy:
  &default-deploy
  resources:
    limits:
      cpus: '0.3'
      memory: 500M

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - 5000:8080
    depends_on:
      postgres-keycloak: 
        condition: service_started
    env_file:
      - env/service/keycloak.env
    deploy:
      << : *default-deploy
      resources:
        limits:
          memory: 1000M

  books-service:
    image: laefad/bookservice-books-service
    container_name: books-service
    build:
      context: .
      target: prod
      dockerfile: ./books-service/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - env/service/books.env
      - env/client/config.env
      - env/client/oauth2-resourceserver.env
    depends_on:
      postgres-books:
        condition: service_started
    deploy: *default-deploy

  postgres-books:
    container_name: postgres-books
    image: postgres:latest
    volumes: 
      - ./postgres-books:/docker-entrypoint-initdb.d
      - postgres-books-source:/var/lib/postgresql/data
    env_file:
      - env/database/books.env
    deploy: *default-deploy

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:latest
    restart: always
    env_file:
      - env/database/keycloak.env
    volumes:
      - postgres-keycloak-source:/var/lib/postgresql/data
    deploy: *default-deploy

volumes:
  postgres-books-source:
    name: postgres-books-source
  postgres-keycloak-source:
    name: postgres-keycloak-source
