version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes: 
      - postgres-source:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPASSWORD: postgres
    ports:
      - "5432:5432"

  pgAdmin:
    container_name: app_pgAdmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - type: volume
        source: pg-admin
        target: /var/lib/pgadmin

volumes:
  postgres-source:
    name: postgres-source
  pg-admin:
    name: pg-admin
